# Generated by Django 2.1.5 on 2019-03-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='testfile',
            new_name='examfile',
        ),
    ]
