# Generated by Django 2.1.5 on 2019-03-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20190315_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='examfile',
            field=models.FileField(blank=True, default='', upload_to='lecture'),
            preserve_default=False,
        ),
    ]
