# Generated by Django 2.1.5 on 2019-03-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20190321_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='교수님')),
            ],
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='evalue',
            field=models.TextField(verbose_name='강의평'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='examfile',
            field=models.FileField(blank=True, upload_to='lecture', verbose_name='족보파일'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=50, verbose_name='강의명'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Professor'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.IntegerField(verbose_name='수강학기'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='year',
            field=models.IntegerField(verbose_name='수강년도'),
        ),
    ]
