# Generated by Django 2.1.5 on 2019-03-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20190326_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='name',
            new_name='p_name',
        ),
    ]
