# Generated by Django 2.1.5 on 2019-03-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20190326_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='p_name',
            new_name='name',
        ),
    ]
