# Generated by Django 2.1.5 on 2019-03-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_auto_20190326_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='professor',
        ),
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ManyToManyField(to='lecture.Professor'),
        ),
    ]
