# Generated by Django 2.1.5 on 2019-06-08 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_auto_20190328_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='professor',
        ),
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='교수님'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
