# Generated by Django 2.1.2 on 2019-01-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190123_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('studentNumber', models.CharField(max_length=8)),
                ('phoneNumber', models.CharField(max_length=15)),
            ],
        ),
    ]
